feat(form): implemtn additional ngxs form plugin directive input
ngxs/store pull request #1840
Opened 2022-05-11 22:11 UTC by rfprod

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #1839

## What is the new behavior?

The ngxs-form plugin directive now has an additional input `ngxsFormPatchEmitEvent` to control [the `form.patchValue` method option `emitEvent`](https://angular.io/api/forms/FormGroup#patchValue).

### Changes summary

- [x] implement the ability to control the form.patchValue emitEvent option;
- [x] add unit test, review jest configs, update jest-preset-angular minor version;
- [x] update the form plugin documentation;

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2022-05-14 21:51 UTC, splincode approved these changes

2022-05-21 21:06 UTC, markwhitfeld requested changes
Thank you for this very thorough PR!
I would like to hold off on merging this until we fully understand the need for this feature.
We would need to understand what use case it is addressing, if there are any workarounds, and how it would enhance the usage of the plugin.
A good place to do this would be in the issue you logged (#1839).

I notice that there are a number of adjustments you made to the jest setup.
If this is a fix to some of the test execution issues you had, then please feel free to split these particular changes into a separate PR to fix jest 👍 .

2022-05-24 21:24 UTC, rfprod commented
> I notice that there are a number of adjustments you made to the jest setup. If this is a fix to some of the test execution issues you had, then please feel free to split these particular changes into a separate PR to fix jest +1 .

A separate PR with unit test changes https://github.com/ngxs/store/pull/1846

2022-08-07 07:51 UTC, arturovt commented
I'll close the PR (for now), since this feature needs discussion and needs some support from the community. At least if that user (in the Slack chat) was experiencing some weird bug, he could report a bug with a reproducible example provided.

2022-08-07 07:51 UTC, closed without merging