docs: introduce schematics
ngxs/store pull request #2057
Opened 2023-09-18 09:48 UTC by profanis

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Other information

2023-09-18 16:06 UTC, arturovt approved these changes

2023-09-25 20:03 UTC, markwhitfeld requested changes
The command to call the schematics should include the package. Eg:

`ng generate @ngxs/store:actions ...`

2023-09-26 10:04 UTC, profanis commented
> The command to call the schematics should include the package. Eg:
> 
> `ng generate @ngxs/store:actions ...`

It's fixed. Can you please have a look at it?

2023-09-26 20:02 UTC, markwhitfeld approved these changes
Great! Approving and merging, but could you add a subsequent PR to clarify the output of the store schematic?
Currently the description in the schematics page doesn't give me a clear idea, and the description of the output on the store page is non-descript.

2023-09-26 20:02 UTC, merged