feat: upgrade to Angular 17, add `selectSignal`
ngxs/store pull request #2087
Opened 2023-11-30 22:51 UTC by arturovt

2023-12-01 13:11 UTC, markwhitfeld commented
@arturovt I see that there is quite a bit of reformatting of files in this PR.
Could you split that reformatting work into a separate PR to make this one easier to review?

2023-12-01 15:50 UTC, arturovt commented
I just ran Nx migration and then when committing changes it ran pre-commit hook and formatted files...

2024-01-30 22:55 UTC, arturovt commented
@markwhitfeld I have reverted formatting changes.

2024-02-01 10:53 UTC, markwhitfeld requested changes
There is so much going on in this PR that it was super difficult to review.
I have a number of suggested changes and questions.
If it is easy to split this into smaller PRs then that would be awesome. If not, then let's press ahead to try to get this PR in.

2024-02-01 10:53 UTC, markwhitfeld commented on integration/app/app.component.ts
> +  injected: Signal<string> = this._store.selectSignal(TodosState.getInjected);
I think that we should have a signal version, and an observable version of this component. WDYT?

2024-02-01 10:53 UTC, markwhitfeld commented on integration/app/app.config.ts
> +      withNgxsLoggerPlugin({ logger: console, collapsed: false, disabled: false }),
Do we want to enable logging as part of this PR?
Or was this just left after some debugging?

2024-02-01 10:53 UTC, markwhitfeld commented on integration/jest.config.js
> +        stringifyContentPathRegex: '\\.(html|svg)$'
Why was this needed?
If it was auto-generated by NX, then it's just their implementation details, but if it was something that was added by us for NGXS, then is this something we should add as guidance in our docs?

2024-02-01 10:53 UTC, markwhitfeld commented on package.json
> +    "test:types": "cd packages/store/types && yarn test:types",
Something to do with this change seems to be failing the tests.
I see that there is a `package.json` file with a `yarn.lock`but no install is run from ci for this folder.
- Potentially we could add a `workspaces` property in the main `package.json` that includes this folder to make that happen, but I'm not sure how `yarn` does it, compared to modern `npm`.
- Or we could modify the `.github/actions/setup/action.yml` file to also run the install from that folder.
- Or we could add a `yarn install... ` command into the types folder's `package.json` to do the install just in time. Just like how we do for the integration apps.

2024-02-01 10:53 UTC, markwhitfeld commented on .github/workflows/trunk.yml
> +          - 'integration:ng16'
Should we add `- 'integration:ng17'` here too?
```suggestion
          - 'integration:ng16'
          - 'integration:ng17'
```

2024-02-01 10:53 UTC, markwhitfeld commented on .github/workflows/release.yml
> +          - 'integration:ng16'
Should we add `- 'integration:ng17'` here too?
```suggestion
          - 'integration:ng16'
          - 'integration:ng17'
```

2024-02-01 10:53 UTC, markwhitfeld commented on .github/workflows/pr-validation.yml
> +        if: ${{ matrix.script == 'integration:ng16' }}
This should run for all integration tests.
```suggestion
        if: ${{ startsWith( matrix.script, 'integration:' ) }}
```

2024-02-01 10:53 UTC, markwhitfeld commented on .github/actions/download-integration-test-artifacts/action.yml
>          path: ${{ inputs.path }}
This step should be repeated for ng 17 too.

2024-02-01 10:53 UTC, markwhitfeld commented on .github/workflows/release.yml
> +        if: ${{ matrix.script == 'integration:ng16' }}
This should run for all integration tests.
```suggestion
        if: ${{ startsWith( matrix.script, 'integration:' ) }}
```

2024-02-01 10:53 UTC, markwhitfeld commented on .github/workflows/trunk.yml
> +        if: ${{ matrix.script == 'integration:ng16' }}
This should run for all integration tests.
```suggestion
        if: ${{ startsWith( matrix.script, 'integration:' ) }}
```

2024-02-01 11:41 UTC, markwhitfeld commented on integration/jest.config.js
> +        stringifyContentPathRegex: '\\.(html|svg)$'
Made by NX

2024-02-05 20:54 UTC, markwhitfeld reviewed
Approved in principle, but we should not merge this until we are building towards the next release that drops support for ng15 and earlier.

2024-02-05 21:52 UTC, markwhitfeld approved these changes
I did a deeper review, and it doesn't look like this will affect our supported Angular versions.

2024-02-05 22:04 UTC, merged