build: add Angular 19 support
ngxs/store pull request #2269
Opened 2024-11-21 12:17 UTC by arturovt

2024-11-21 14:23 UTC, rhutchison approved these changes

2024-11-22 11:11 UTC, markwhitfeld commented on .circleci/config.yml
> +  integration_ng19_tests:
This job needs to be added to the `build-workflow`.

2024-11-24 16:19 UTC, markwhitfeld requested changes
Great work, but it seems that in the following file:
`packages\store\experimental\src\pending-tasks.ts`
We import `ExperimentalPendingTasks` from `@angular/core`.
In Angular 19, this is now available as `PendingTasks` from `@angular/core`.

This means that we can move the `withExperimentalNgxsPendingTasks` utility from the `@ngxs/store/experimental` sub package to `withNgxsPendingTasks` in the main `@ngxs/store` package (unless you can think of a more ideal place?).
Related to this change would be a version bump of NGXS v18 to NGXS v19 (especially because of this breaking change)🎉

2024-11-24 17:30 UTC, arturovt commented
I agree.

2024-11-24 17:34 UTC, arturovt commented
But we should wait until the Nx allows migrating to Angular 19 in order to update the workspace version too.

2024-11-25 06:57 UTC, markwhitfeld commented
What is the dependency on NX which would be blocking us?
Can we not release an NGXS v19 independently of the version of NX?
Surely we can do the workspace update separately.

PS. We should still keep the experimental subpackage around. 
We can export the `withExperimentalNgxsPendingTasks` with a deprecation notice. This function would just use the `withNgxsPendingTasks` function that has moved to the main package.

2024-11-25 11:35 UTC, arturovt commented
We can but not with the pending tasks change. The workspace is using Angular 18 which doesn't expose `PendingTasks` from the core.

2024-11-25 11:48 UTC, markwhitfeld commented
Ok, so we are blocked until this NX PR is merged:
https://github.com/nrwl/nx/pull/28847
That NX PR is, in turn blocked by a number of their dependencies, waiting for upgrade.

Is there any way that we can decouple the angular version that our libraries reference from the version of NX?
I'm wondering if there is something we can do with overrides in the `package.json`, or if we could use the aliasing functionality of tsconfigs to "redirect" the referenced angular version use in our libraries?
What we build with doesn't necessarily determine what our code references. Any ideas?

2024-11-25 12:05 UTC, arturovt commented
> We can export the withExperimentalNgxsPendingTasks with a deprecation notice.

This would throw an error that ` Entry point @ngxs/store has a circular dependency on itself.`

2024-11-25 12:11 UTC, markwhitfeld commented
The experimental subpackage already references things from the
***@***.***/store` library.
We would be moving the functionality to the core lib and referencing it
there (having the same direction of reference as the existing refs).

On Mon, 25 Nov 2024 at 14:05, Artur ***@***.***> wrote:

> We can export the withExperimentalNgxsPendingTasks with a deprecation
> notice.
>
> This would throw an error that Entry point @ngxs/store has a circular
> dependency on itself.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ngxs/store/pull/2269#issuecomment-2497834161>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAO3U2JKPHI3EQNN5W72HFT2CMHALAVCNFSM6AAAAABSG3RGQSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOJXHAZTIMJWGE>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-11-25 12:17 UTC, arturovt commented
I have looked at what NgRx did, they upgraded workspace version w/o waiting for the Nx upgrade.

I upgraded the workspace version and had to update unit tests because components are standalone by default now.

2024-11-25 12:33 UTC, markwhitfeld commented
Great work!
There may be some usefulness to still have some components as `standalone:
false` where we are testing things about modules, but I think that most can
be converted.


On Mon, 25 Nov 2024 at 14:17, Artur ***@***.***> wrote:

> I have looked at what NgRx did, they upgraded workspace version w/o
> waiting for the Nx upgrade.
>
> I upgraded the workspace version and had to update unit tests because
> components are standalone by default now.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ngxs/store/pull/2269#issuecomment-2497860897>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAO3U2IAAR42EOPBCQ5GTWT2CMIO3AVCNFSM6AAAAABSG3RGQSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOJXHA3DAOBZG4>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-11-25 14:15 UTC, arturovt commented
@markwhitfeld what do we with ng16/17/18 integrations? They're not compatible anymore because we're using `PendingTasks`. Do we remove them completely because we want to bump the version to `ngxs@19` and make it compatible with `angular >= 19.0.0`?

2024-11-28 04:12 UTC, tejasv-tagline commented
Is anyone taking care of changes for this PR? Many users are waiting for Angular 19 support.

2024-11-28 20:22 UTC, markwhitfeld requested changes

2024-11-28 20:22 UTC, markwhitfeld commented on packages/store/experimental/src/pending-tasks.ts
> +export { withNgxsPendingTasks as withExperimentalNgxsPendingTasks } from '@ngxs/store';
```suggestion
import { withNgxsPendingTasks } from '@ngxs/store';

/**
 * Required for correct functioning of SSR apps. 
 *
 * @deprecated
 * This experimental export is deprecated in favour of the non-experimental export. This is no longer an experimental feature, but is now available as `withNgxsPendingTasks` in the main `@ngxs/store` package.
 */
export function withExperimentalNgxsPendingTasks () {
  return withNgxsPendingTasks(); 
}
```

2024-11-28 20:22 UTC, markwhitfeld commented on packages/store/src/pending-tasks.ts
> + * This feature that contributes to app stability, * which is required during
```suggestion
 * This feature that contributes to app stability, which is required during
```

2024-11-28 20:22 UTC, markwhitfeld commented on packages/store/src/pending-tasks.ts
> + */
```suggestion
  * Including `withNgxsPendingTasks` in your `provideStore` for your SSR app will resolve the above issue.
  */
```

2024-11-28 20:22 UTC, markwhitfeld commented on packages/store/experimental/tests/preboot-wait-stable.spec.ts
We should add this test to the main package's tests.

2024-11-29 09:35 UTC, markwhitfeld approved these changes
Great work!!!!
Let's get this released!

2024-11-29 09:37 UTC, merged